### ISSUE TITLE
Bug in F-Fisher distribution

### ISSUE THREAD

**Issue by JosheZhuh** [jonathon-love/distrACTION#10]
To whom it may concern,

Hello! My name is José Granados. I am currently using Jamovi in the Linux version (I downloaded it this summer) and I guess there is a bug in the distrACTION module. More precisely, when you ask Jamovi to compute a quantile from de F of Fisher distribution, in the Results area it appears an error message telling the following:
'attempt to set 'colnames' on an object with less than two dimensions'
I guess it is a syntax error in the code.
I have checked the same procedure in Windows and Mac versions and it works fine, there is no error.

Thank you for your attention and sorry for the inconvenience.

Best wishes,
José

**Comment by cmontgo** [comment]
Ah, I see it. I think I know why. Will push a fix soon, thanks

**Comment by cmontgo** [comment]
Fixed. Looks like I had a random letter p in the code. Removed

**Comment by JosheZhuh** [comment]
Thank you very much!
Best wishes,
José
________________________________
De: cmontgo ***@***.***>
Enviado: domingo, 18 de septiembre de 2022 2:53
Para: methodenlehre/distrACTION ***@***.***>
Cc: JosheZhuh ***@***.***>; Author ***@***.***>
Asunto: Re: [methodenlehre/distrACTION] Bug in F-Fisher distribution (Issue #10)


Fixed. Looks like I had a random letter p in the code. Removed

**Comment by JosheZhuh** [comment]
Ok! So now I guess we have to wait to the update of the module and then reinstall the module in Jamovi, don't we?
________________________________
De: cmontgo ***@***.***>
Enviado: domingo, 18 de septiembre de 2022 2:53
Para: methodenlehre/distrACTION ***@***.***>
Cc: JosheZhuh ***@***.***>; Author ***@***.***>
Asunto: Re: [methodenlehre/distrACTION] Bug in F-Fisher distribution (Issue #10)


Fixed. Looks like I had a random letter p in the code. Removed

**Comment by cmontgo** [comment]
It should come as a 1.1.1 update (should be available now), check in the modules tab
